### ISSUE TITLE
'.jpg' file extension returns 'application/octet-stream' when using GetMimeType

### ISSUE THREAD

**Issue by Jake-Roper** [lettucebo/MimeTypeMap.List#4] opened 2019-05-22 15:25 UTC
I'm currently feeding through file extensions into the GetMimeType method using a comma separated string, which currently consists of `.pdf, .jpg`. The first extension returns the correct type of `application/pdf`, but the second extension returns the type `application/octet-stream`, from which I can see via the code, is returned if the mime type/extension could not be found within the mappings. 

I can definitely see the correct mapping within the MappingList.cs however.

**Comment by lettucebo** [comment] 2019-10-25 11:00
Hi

I try the the way you say, but I can't reproduce this situation, no matter use .netcore or .net

and even with ".jpg" still return the correct mime

![image](https://user-images.githubusercontent.com/891383/67566127-97a78900-f759-11e9-867d-0e2015ceb327.png)

So I'm going to close this issue right now, if you still have same issue please let me know

**Closed as completed by lettucebo** 2019-10-25 11:00 UTC
